## AI Programming Foundations Project

## Name: Sayed Saidoo

## Dataset: Wine(Chemical properties and quality scores)

## Project Overview

This project demonstrates a reproducible data analysis workflow using the Wine Quality datasets for Portuguese "Vinho Verde" red and white wines. The workflow includes data ingestion, cleaning, exploratory analysis, visualization, and interpretation using Python, Pandas, Numpy, Matplotlib, and Seaborn.

The objective is to explore how physicochemical properties relate to expert-rated wine quality and to compare patterns between red and white wines.

### Core Dependencies and Data Ingestion

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment Ready")

Environment Ready

In [14]:
df_red = pd.read_csv("../data/winequality-red.csv", sep=";")
df_red.sample(7)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
734,7.7,0.56,0.20,2.0,0.075,9.0,39.0,0.99870,3.48,0.62,9.3,5
1340,7.5,0.51,0.02,1.7,0.084,13.0,31.0,0.99538,3.36,0.54,10.5,6
778,8.3,0.43,0.30,3.4,0.079,7.0,34.0,0.99788,3.36,0.61,10.5,5
832,10.4,0.44,0.42,1.5,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3
1273,7.5,0.58,0.20,2.0,0.073,34.0,44.0,0.99494,3.10,0.43,9.3,5
121,8.8,0.55,0.04,2.2,0.119,14.0,56.0,0.99620,3.21,0.60,10.9,6
892,10.1,0.45,0.23,1.9,0.082,10.0,18.0,0.99774,3.22,0.65,9.3,6

In [13]:
df_white = pd.read_csv("../data/winequality-white.csv", sep=";")
df_white.sample(7)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1369,7.4,0.64,0.47,14.15,0.168,42.0,185.0,0.99840,2.90,0.49,9.3,5
363,7.3,0.22,0.37,14.30,0.063,48.0,191.0,0.99780,2.89,0.38,9.0,6
3467,6.6,0.24,0.27,10.30,0.047,54.0,219.0,0.99742,3.04,0.45,8.8,5
2046,8.3,0.33,0.43,9.20,0.046,22.0,126.0,0.99820,3.38,0.47,9.3,5
3865,6.0,0.31,0.38,4.80,0.040,41.0,101.0,0.98968,3.24,0.56,13.1,6
362,6.8,0.15,0.30,5.30,0.050,40.0,127.0,0.99420,3.40,0.39,9.7,6
3407,6.1,0.33,0.32,7.80,0.052,52.0,183.0,0.99657,3.39,0.65,9.5,5

### Data Inspection and Cleaning

In [9]:
print(df_red.shape)
print(df_white.shape)

(1599, 12)
(4898, 12)

In [10]:
df_red.info()

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [11]:
df_white.info()

<class 'pandas.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

- Initial inspection of both datasets showed that all columns were assigned appropriate numeric data types and no missing values were detected. This suggests the datasets are relatively clean and suitable for analysis, though additional validation checks such as duplicate detection and consistency checks will still be performed.

In [16]:
# Check for duplicate rows
print(f"Red wine duplicates: {df_red.duplicated().sum()}")
print(f"White wine duplicates: {df_white.duplicated().sum()}")

# Verify column names match
print(df_red.columns.equals(df_white.columns))

# Verify data types match
print(df_red.dtypes.equals(df_white.dtypes))

Red wine duplicates: 240
White wine duplicates: 937
True
True

In [17]:
duplicates_red = df_red[df_red.duplicated()]
duplicates_white = df_white[df_white.duplicated()]

In [27]:
duplicates_red.sample(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
914,7.3,0.305,0.39,1.2,0.059,7.0,11.0,0.99331,3.29,0.52,11.5,6
1563,7.2,0.695,0.13,2.0,0.076,12.0,20.0,0.99546,3.29,0.54,10.1,5
1084,7.2,0.380,0.30,1.8,0.073,31.0,70.0,0.99685,3.42,0.59,9.5,6
1560,7.8,0.600,0.26,2.0,0.080,31.0,131.0,0.99622,3.21,0.52,9.9,5
27,7.9,0.430,0.21,1.6,0.106,10.0,37.0,0.99660,3.17,0.91,9.5,5

In [23]:
duplicates_white.sample(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4828,6.4,0.23,0.35,10.3,0.042,54.0,140.0,0.99670,3.23,0.47,9.200000,5
4850,7.0,0.36,0.35,2.5,0.048,67.0,161.0,0.99146,3.05,0.56,11.100000,6
4851,6.4,0.33,0.44,8.9,0.055,52.0,164.0,0.99488,3.10,0.48,9.600000,5
4856,7.1,0.23,0.39,13.7,0.058,26.0,172.0,0.99755,2.90,0.46,9.000000,6
4880,6.6,0.34,0.40,8.1,0.046,68.0,170.0,0.99494,3.15,0.50,9.533333,6

- Duplicate rows were identified during the initial inspection and will be removed to improve data quality and prevent repeated observations from influencing the analysis.

- A consistency check was performed prior to merging the datasets. Both datasets contain the same columns and data types, indicating they can be combined safely without requiring structural modifications.

- The consistency check suggests that the red and white wine datasets can be merged into a single dataset for analysis. Adding a wine type indicator will allow comparisons between wine classes while preserving information about the original source of each observation.

In [35]:
def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """
    Remove duplicate rows from a dataframe.
    
    Parameters:
    df (pd.DataFrame): Input dataframe.
    
    Returns:
    pd.DataFrame: Dataframe with duplicate rows removed.
    
    """
    return df.drop_duplicates()

In [29]:
df_red = remove_duplicates(df_red)
df_white = remove_duplicates(df_white)

In [44]:
def add_wine_type(df: pd.DataFrame, wine_type: str) -> pd.DataFrame:
    """
    Add a wine type identifier to a dataframe.
     
    Parameters:
    
        df (pd.DataFrame): Input dataframe.
        wine_type (str): Label indicating the wine type.
    
    Returns:
        pd.DataFrame: Dataframe with a new wine_type column.
    
    """
    df = df.copy()
    df["wine_type"] = wine_type
    return df

In [31]:
df_red = add_wine_type(df_red, "Red")
df_white = add_wine_type(df_white, "White")

In [33]:
df_red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,wine_type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,Red

In [34]:
df_white.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,wine_type
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,White
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,White
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,White
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,White
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.9949,3.18,0.47,9.6,6,White

- A wine_type column was added prior to merging the datasets so that observations from red and white wines could be distinguished after consolidation.
This preserves the origin of each record and enables comparative analysis between wine classes.

In [37]:
def merge_wine_datasets(df_red: pd.DataFrame, df_white: pd.DataFrame) -> pd.DataFrame:
    """
    Merge the red and white wine datasets into a single dataframe.
    
    Parameters:
        df_red (pd.DataFrame): Cleaned red wine dataframe.
        df_white (pd.DataFrame): Cleaned white wine dataframe.
     
    Returns:
        pd.DataFrame: Combined wine dataframe.
    """
    return pd.concat([df_red, df_white], ignore_index=True)

In [38]:
df_wine = merge_wine_datasets(df_red, df_white)

In [45]:
# Confirmation of merge success
df_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,wine_type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red
4,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,Red

In [46]:
# Sanity check for white wine rows
df_wine.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,wine_type
5315,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,White
5316,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,White
5317,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,White
5318,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,White
5319,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,White

### Exploratory Data Analysis